"""empty message

Revision ID: 02a1dd24a267
Revises: 8196a40f7348
Create Date: 2025-02-23 13:22:23.985758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a1dd24a267'
down_revision = '8196a40f7348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('searchable', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locale', schema=None) as batch_op:
        batch_op.drop_column('searchable')

    # ### end Alembic commands ###
