"""empty message

Revision ID: 8196a40f7348
Revises: 
Create Date: 2025-02-23 12:58:09.324547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8196a40f7348'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=30), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eng_word', sa.String(length=20), nullable=False),
    sa.Column('eng_pos', sa.String(length=30), nullable=False),
    sa.Column('eng_meaning', sa.String(length=60), nullable=False),
    sa.Column('local_word', sa.String(length=20), nullable=False),
    sa.Column('local_pos', sa.String(length=30), nullable=False),
    sa.Column('local_meaning', sa.String(length=60), nullable=False),
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('locale')
    # ### end Alembic commands ###
